export const Navbar =[
    {
        NavYoz1:"Home",
        ok:false,
        hr:'#home'
    },
    {
        NavYoz1:"about",
        ok:false,
        hr:'#about'
    },
    {
        NavYoz1:"Servise",
        ok:false,
        hr:'#servise'
    },
    {
        NavYoz1:"Portfolio",
        ok:false,
        hr:'#depart'
    },
    {
        NavYoz1:"Team",
        ok:false,
        hr:'#doctors'
    },
    {
        NavYoz1:"Drop Down",
        ok:true
    },
    {
        NavYoz1:"CONTACT",
        ok:false,
        hr:'#contact'
    },
]